spring:
  profiles:
    active: dev #by default, active prof is "dev". during production replaced to prod
  web:
    resources:
      add-mappings: false
api:
  endpoint:
    base-url: /api/v1

server:
  port: 80
